"""CUTLASS-backed 2:4 structured sparse Linear helpers."""

from __future__ import annotations

import torch

from .cutlass_backend import (
    dense_cutlass_device_gemm,
    dense_cutlass_routed_rows_weight_t,
    dense_cutlass_simt_weight_t_gemm,
    dense_cutlass_weight_t_gemm,
    dense_cutlass_weight_t_gemm_add,
    prepare_cutlass_sparse24_gate_up_swiglu,
    prepare_cutlass_sparse24_pair_add,
    prepare_cutlass_sparse24_device_gemm,
    sparse24_add_indexed_rows_contiguous_,
    sparse24_add_indexed_rows_transposed_to_contiguous_,
    sparse24_sub_indexed_rows_contiguous_,
    sparse24_add_indexed_rows_strided_,
    sparse24_add_prefix_strided_,
    sparse24_copy_indexed_rows_contiguous_,
    sparse24_copy_indexed_rows_strided_,
    sparse24_cutlass_device_gemm,
    sparse24_cutlass_device_gemm_prepacked,
    sparse24_cutlass_device_splitk_indexed_add_gemm_prepacked,
    sparse24_cutlass_device_splitk_gemm_prepacked,
    sparse24_cutlass_device_strided_input_gemm_prepacked,
    sparse24_cutlass_dual_swiglu_prepacked,
    sparse24_cutlass_full_sparse_dense_override_linear_prepacked,
    sparse24_cutlass_full_sparse_dense_override_swiglu_prepacked,
    sparse24_cutlass_gather_gemm_prepacked,
    sparse24_cutlass_gate_up_swiglu_prepacked,
    sparse24_cutlass_gate_dense_down_pipeline_prepacked,
    sparse24_cutlass_gate_sparse_down_pipeline_prepacked,
    sparse24_cutlass_heterogeneous_linear_prepacked,
    sparse24_cutlass_heterogeneous_swiglu_prepacked,
    sparse24_cutlass_grouped_owner_linear_prepacked,
    sparse24_cutlass_grouped_owner_qkv_prepacked,
    sparse24_cutlass_grouped_owner_swiglu_prepacked,
    sparse24_cutlass_indexed_output_gemm_prepacked,
    sparse24_cutlass_indexed_swiglu_prepacked,
    sparse24_cutlass_inline_transpose_gemm_prepacked,
    sparse24_cutlass_pair_add_indexed_prepacked,
    sparse24_cutlass_paired_gather_routed_swiglu_prepacked,
    sparse24_cutlass_paired_gather_residual_prepacked,
    sparse24_cutlass_paired_gather_residual_qkv_prepacked,
    sparse24_cutlass_paired_fused_routed_qkv_epilogue_prepacked,
    sparse24_cutlass_paired_fused_routed_swiglu_prepacked,
    sparse24_cutlass_fused_mixed_mlp_prepacked,
    sparse24_cutlass_paired_self_contained_exact_down_prepacked,
    sparse24_cutlass_paired_self_contained_routed_swiglu_prepacked,
    sparse24_cutlass_paired_finalize_qkv_prepacked,
    sparse24_cutlass_paired_finalize_residual_prepacked,
    sparse24_cutlass_paired_inplace_residual_prepacked,
    sparse24_cutlass_paired_persistent_gemm_prepacked,
    sparse24_cutlass_paired_persistent_routed_swiglu_prepacked,
    sparse24_cutlass_qkv_postop_prepacked,
    sparse24_cutlass_residual_correction_swiglu_prepacked,
    sparse24_cutlass_residual_delta_swiglu_prepacked,
    sparse24_cutlass_routed_exact_linear_prepacked,
    sparse24_cutlass_routed_exact_swiglu_prepacked,
    sparse24_cutlass_routed_output_gemm_prepacked,
    sparse24_cutlass_routed_residual_epilogue_prepacked,
    sparse24_cutlass_routed_sparse_rows_prepacked,
    sparse24_cutlass_routed_swiglu_prepacked,
    sparse24_gather_rows_,
    sparse24_gather_rows_strided_,
    sparse24_merge_rows_,
    sparse24_mixed_dense_override_prepacked,
    sparse24_partition_rows_,
    sparse24_qkv_add_routed_residual_postop_cache_inplace_,
    sparse24_qkv_add_routed_residual_postop_inplace_,
    sparse24_qkv_rmsnorm_inplace_,
    sparse24_qkv_transpose_add_routed_residual_postop,
    sparse24_qkv_transpose_postop,
    sparse24_qkv_transpose_rmsnorm,
    sparse24_routed_linear_correction_,
    sparse24_routed_swiglu_correction_,
    sparse24_routed_swiglu_correction_gather_,
    sparse24_routed_swiglu_correction_transpose,
    sparse24_routed_swiglu_delta_,
    sparse24_silu_and_mul_transposed,
    sparse24_silu_and_mul_transposed_to_contiguous,
    sparse24_cutlass_signal_ready_,
    sparse24_transpose_add_residual_,
    sparse24_transpose_add_routed_residual,
    sparse24_transpose_add_routed_residual_rmsnorm,
    sparse24_transpose_add_routed_residual_to_residual_,
    sparse24_transpose_add_routed_splitk_residual,
    sparse24_transpose_add_rmsnorm,
    sparse24_transpose_input_to_strided,
    sparse24_transpose_output_contiguous,
)
from .pack import (
    PATTERN_TO_POS,
    PATTERN_TO_ORDERED_META_NIBBLE,
    Packed24Weight,
    Sparse24Layout,
    apply_random_24_mask,
    assert_24_weight,
    decompress_24,
    pack_mma_sp_operand_a,
    pack_ordered_metadata_u32,
    pack_24,
    pack_24_from_n_major_group_bytes,
    pattern_meta_to_ordered_nibbles,
)


def sparse_mma_status() -> dict[str, object]:
    """Return local sparse-MMA capability and selected runtime backend."""

    cuda_available = torch.cuda.is_available()
    capability = torch.cuda.get_device_capability(0) if cuda_available else None
    hardware_supported = bool(capability is not None and capability[0] >= 8)
    return {
        "matrix_backend_available": True,
        "backend": "cutlass_device_sparse_gemm_view",
        "backend_uses_mma_sp": True,
        "supports_prepacked_weights": True,
        "device_sparse_gemm_alignment": (
            "fp16, K % 64 == 0, N % 32 == 0; M is padded to a multiple "
            "of 8 internally"
        ),
        "device_sparse_gemm_configs": (
            "auto, 64x32x64_s3, 64x32x64_s4, 64x32x64_s5, "
            "64x64x64, 64x64x64_s4, 64x64x64_s5, "
            "64x64x64_s6, 64x64x64_s7, 64x128x64_s4, "
            "128x32x64_s4, 128x32x64_s4_sw2, 128x32x64_s4_sw4, "
            "128x64x64_s3, 128x64x64_s4, 128x64x64_s5, "
            "128x128x64_s3, 128x128x64_s3_sw2, 128x128x64_s3_sw4, "
            "256x64x64_s3, 256x64x64_s3_sw2, 256x64x64_s3_sw4"
        ),
        "default_output": (
            "non-contiguous [M, N] view over CUTLASS's internal row-major "
            "C[N, M] storage"
        ),
        "contiguous_output": (
            "available through contiguous_output=True; this adds a tiled "
            "transpose after SparseGemm"
        ),
        "cuda_available": cuda_available,
        "compute_capability": capability,
        "hardware_sparse_tensorcore_supported": hardware_supported,
    }


def sparse24_matmul(
    X: torch.Tensor,
    values: torch.Tensor,
    meta: torch.Tensor,
    *,
    layout: Sparse24Layout = "k_major",
    contiguous_output: bool = False,
    pad_m_multiple: int | None = None,
) -> torch.Tensor:
    """Compute ``Y = X @ W24`` through the CUTLASS SparseGemm backend."""

    return sparse24_cutlass_device_gemm(
        X,
        values,
        meta,
        layout=layout,
        contiguous_output=contiguous_output,
        pad_m_multiple=pad_m_multiple,
    )

__all__ = [
    "PATTERN_TO_POS",
    "PATTERN_TO_ORDERED_META_NIBBLE",
    "Packed24Weight",
    "Sparse24Layout",
    "apply_random_24_mask",
    "assert_24_weight",
    "dense_cutlass_device_gemm",
    "dense_cutlass_routed_rows_weight_t",
    "dense_cutlass_simt_weight_t_gemm",
    "dense_cutlass_weight_t_gemm",
    "dense_cutlass_weight_t_gemm_add",
    "decompress_24",
    "pack_mma_sp_operand_a",
    "pack_ordered_metadata_u32",
    "pack_24",
    "pack_24_from_n_major_group_bytes",
    "pattern_meta_to_ordered_nibbles",
    "sparse24_matmul",
    "prepare_cutlass_sparse24_device_gemm",
    "prepare_cutlass_sparse24_gate_up_swiglu",
    "prepare_cutlass_sparse24_pair_add",
    "sparse24_add_indexed_rows_contiguous_",
    "sparse24_add_indexed_rows_transposed_to_contiguous_",
    "sparse24_sub_indexed_rows_contiguous_",
    "sparse24_add_indexed_rows_strided_",
    "sparse24_add_prefix_strided_",
    "sparse24_copy_indexed_rows_contiguous_",
    "sparse24_copy_indexed_rows_strided_",
    "sparse24_cutlass_device_gemm",
    "sparse24_cutlass_device_gemm_prepacked",
    "sparse24_cutlass_device_splitk_indexed_add_gemm_prepacked",
    "sparse24_cutlass_device_splitk_gemm_prepacked",
    "sparse24_cutlass_device_strided_input_gemm_prepacked",
    "sparse24_cutlass_dual_swiglu_prepacked",
    "sparse24_cutlass_full_sparse_dense_override_linear_prepacked",
    "sparse24_cutlass_full_sparse_dense_override_swiglu_prepacked",
    "sparse24_cutlass_gather_gemm_prepacked",
    "sparse24_cutlass_gate_up_swiglu_prepacked",
    "sparse24_cutlass_gate_dense_down_pipeline_prepacked",
    "sparse24_cutlass_gate_sparse_down_pipeline_prepacked",
    "sparse24_cutlass_heterogeneous_linear_prepacked",
    "sparse24_cutlass_heterogeneous_swiglu_prepacked",
    "sparse24_cutlass_grouped_owner_linear_prepacked",
    "sparse24_cutlass_grouped_owner_qkv_prepacked",
    "sparse24_cutlass_grouped_owner_swiglu_prepacked",
    "sparse24_cutlass_indexed_output_gemm_prepacked",
    "sparse24_cutlass_indexed_swiglu_prepacked",
    "sparse24_cutlass_inline_transpose_gemm_prepacked",
    "sparse24_cutlass_pair_add_indexed_prepacked",
    "sparse24_cutlass_paired_gather_routed_swiglu_prepacked",
    "sparse24_cutlass_paired_gather_residual_prepacked",
    "sparse24_cutlass_paired_gather_residual_qkv_prepacked",
    "sparse24_cutlass_paired_fused_routed_qkv_epilogue_prepacked",
    "sparse24_cutlass_paired_fused_routed_swiglu_prepacked",
    "sparse24_cutlass_fused_mixed_mlp_prepacked",
    "sparse24_cutlass_paired_self_contained_exact_down_prepacked",
    "sparse24_cutlass_paired_self_contained_routed_swiglu_prepacked",
    "sparse24_cutlass_paired_finalize_qkv_prepacked",
    "sparse24_cutlass_paired_finalize_residual_prepacked",
    "sparse24_cutlass_paired_inplace_residual_prepacked",
    "sparse24_cutlass_paired_persistent_gemm_prepacked",
    "sparse24_cutlass_paired_persistent_routed_swiglu_prepacked",
    "sparse24_cutlass_qkv_postop_prepacked",
    "sparse24_cutlass_residual_correction_swiglu_prepacked",
    "sparse24_cutlass_residual_delta_swiglu_prepacked",
    "sparse24_cutlass_routed_exact_linear_prepacked",
    "sparse24_cutlass_routed_exact_swiglu_prepacked",
    "sparse24_cutlass_routed_output_gemm_prepacked",
    "sparse24_cutlass_routed_residual_epilogue_prepacked",
    "sparse24_cutlass_routed_sparse_rows_prepacked",
    "sparse24_cutlass_routed_swiglu_prepacked",
    "sparse24_gather_rows_",
    "sparse24_gather_rows_strided_",
    "sparse24_merge_rows_",
    "sparse24_mixed_dense_override_prepacked",
    "sparse24_partition_rows_",
    "sparse24_qkv_add_routed_residual_postop_cache_inplace_",
    "sparse24_qkv_add_routed_residual_postop_inplace_",
    "sparse24_qkv_rmsnorm_inplace_",
    "sparse24_qkv_transpose_add_routed_residual_postop",
    "sparse24_qkv_transpose_postop",
    "sparse24_qkv_transpose_rmsnorm",
    "sparse24_routed_linear_correction_",
    "sparse24_routed_swiglu_correction_",
    "sparse24_routed_swiglu_correction_gather_",
    "sparse24_routed_swiglu_correction_transpose",
    "sparse24_routed_swiglu_delta_",
    "sparse24_silu_and_mul_transposed",
    "sparse24_silu_and_mul_transposed_to_contiguous",
    "sparse24_cutlass_signal_ready_",
    "sparse24_transpose_add_residual_",
    "sparse24_transpose_add_routed_residual",
    "sparse24_transpose_add_routed_residual_rmsnorm",
    "sparse24_transpose_add_routed_residual_to_residual_",
    "sparse24_transpose_add_routed_splitk_residual",
    "sparse24_transpose_add_rmsnorm",
    "sparse24_transpose_input_to_strided",
    "sparse24_transpose_output_contiguous",
    "sparse_mma_status",
]
